version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - run: make build

    deploy_staging:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on staging server
                  command: HOSTNAME=$STAGING_HOSTNAME PORT=$STAGING_PORT VERSION="5.0" make deploy

    deploy_production:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on production server
                  command: HOSTNAME=$PROD_HOSTNAME PORT=$PROD_PORT VERSION="5.0" make deploy

orbs:
    pull-up: akeneo-orbs/pull-up@1.0

workflows:
    version: 2
    pull_request:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - "5.0"

    deployment:
        jobs:
            - deploy_staging:
                  filters:
                      branches:
                          only: "5.0"
            - approve_to_deploy_in_production:
                  type: approval
                  requires:
                      - deploy_staging
            - deploy_production:
                  requires:
                      - approve_to_deploy_in_production

    pull_up:
        jobs:
            - pull-up/pull-up:
                  from: "5.0"
                  into: "master"
                  branch_prefix: "50_to_master"
                  github_token: MICHEL_TAG_TOKEN
                  github_username: "micheltag"
                  slack_webhook: "${SLACK_URL_PULL_UP}"
                  filters:
                      branches:
                          only:
                              - "5.0"
